DROP ТАВLЕ I F EXISTS CONTACT;
CREATE TABLE CONTACT (
ID INT NOT NULL AUTO INCREMENT
, FIRST_NAМE VARCНAR(60) NOT NULL
, LAST_NAМE VARCНAR(40) NOT NULL
, BIRTH DATE DATE
, VERSION INT NOT NULL DEFAULT О
, UNIQUE UQ_CONTACT_l (FIRST_NAМE, LAST_NAМE)
, PRIМARY КЕУ (ID)
);

CREATE TABLE CONTACT_AUDIT_H (
I D INT NOT NULL
) ;
, FIRST NAМE VARCНAR ( 60) NOT NULL
, LAST_NAМE VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, VERSION INT NOT NULL DEFAULT О
, CREATED BY VARCНAR ( 20)
, CREATED DATE TIMESTAМP
, LAST_MODIFIED_BY VARCHAR(20)
, LAST MODIFIED DATE TIMESTAМP
, AUDIT REVISION INТ NOT NULL
, ACTION_ТYPE INТ
, AUDIT REVISION _ END INT
, AUDIT_REVISION_END_TS ТIМЕSТАМР
, UNIQUE UQ_CONTACT_AUDIT_H_l (FIRST_NAМE, LAST NАМЕ)
, PRIМARY КЕУ (ID, AUDIT_REVISION)