DROP ТАВLЕ I F EXISTS CONTACT;
CREATE TABLE CONTACT (
ID INT NOT NULL AUTO INCREMENT
, FIRST_NAМE VARCНAR(60) NOT NULL
, LAST_NAМE VARCНAR(40) NOT NULL
, BIRTH DATE DATE
, VERSION INT NOT NULL DEFAULT О
, UNIQUE UQ_CONTACT_l (FIRST_NAМE, LAST_NAМE)
, PRIМARY КЕУ (ID)
);